### ISSUE TITLE
CopperMountain M5180 -- typo in __init__ docstring?

### ISSUE THREAD

**Issue by omajoshi** [QCoDeS/Qcodes_contrib_drivers#120]
https://github.com/QCoDeS/Qcodes_contrib_drivers/blob/2fd9c391458417e3914b0ca4495ffb4174497bf1/qcodes_contrib_drivers/drivers/CopperMountain/M5180.py#L207

Every line in the file says M5180 except this one, which says S5180. Is that just a typo in the `__init__` docstring?

**Comment by jenshnielsen** [comment]
I am not very familar with this driver but that does seem likely. Are you willing to open a pull request to fix that?

**Comment by omajoshi** [comment]
Going to test the driver on the M5180 first and will make the fix if it works.

**Comment by omajoshi** [comment]
I'm going to compare the driver to the documentation for the M5180, and I'll will make the fix if everything checks out.

**Comment by simonzihlmann** [comment]
I confirm that it is a typo in the docstring and that the driver has been written for the M5180 model. I can fix it at the same time when I propose some changes (I have some minor changes (updated validators, changes to the PointMagPhase class) that I have not yet put into a PR.  Try to do this soonish.

**Comment by jenshnielsen** [comment]
Thanks @simonzihlmann For some reason the original commits no longer map to your github user name (did you change your email perhaps) So I was struggeling with remembering how to mention you but great that you saw it

**Comment by simonzihlmann** [comment]
> Thanks @simonzihlmann For some reason the original commits no longer map to your github user name (did you change your email perhaps) So I was struggeling with remembering how to mention you but great that you saw it

Not on purpose. But it could be that I used a different email address when committing than the one that github knows about. I have added the second one to my profile. Not sure if it has something to do with this though.

**Comment by jenshnielsen** [comment]
Hmn not sure what happened anyway its showing correctly now https://github.com/QCoDeS/Qcodes_contrib_drivers/commits/master/qcodes_contrib_drivers/drivers/CopperMountain/M5180.py?author=simonzihlmann
