### ISSUE TITLE
Latest versions of packaging break QDAC2 driver

### ISSUE THREAD

**Issue by maij** [QCoDeS/Qcodes_contrib_drivers#189]
Somewhere in the recent changes of packaging, using `packaging.version.parse` on strings like 'w-x.y.z' raises an error about an invalid firmware version. Explicitly installing an older version (I used packaging 20.0) circumvents this issue.

**Comment by jenshnielsen** [comment]
@maij This was resolved in #180 and will be part of the next release

**Comment by jenshnielsen** [comment]
I just created a new release that should be available from pypi soon

**Comment by jenshnielsen** [comment]
@maij if you can confirm that resolves the issue we can close this one

**Comment by jenshnielsen** [comment]
Have not heard back so assuming this is indeed fixed by latest release
