### ISSUE TITLE
NationalInstruments drivers missing when installing using pip

### ISSUE THREAD

**Issue by mluessi** [QCoDeS/Qcodes_contrib_drivers#61]
For some reason, the NationalInstruments folder and the drivers it contains are missing for me.

I tried the following:

Install version 0.5.0:

    pip install qcodes_contrib_drivers

Install latest version from github:

    pip install git+https://github.com/QCoDeS/Qcodes_contrib_drivers.git

In both cases, the drivers folder does not contain the NationalInstruments folder. Any ideas?

![image](https://user-images.githubusercontent.com/647005/87854519-6f535200-c8c7-11ea-91c0-e9df5dc99c84.png)

**Comment by jenshnielsen** [comment]
It looks like the NationalInstruments folder is missing an empty ``__init__.py`` file. @mluessi it would be great if you can create a pr to add that file

**Comment by jenshnielsen** [comment]
fixed by #62
